### ISSUE TITLE
2.3.5 Regression

### ISSUE THREAD

**Issue by BuildAndDestroy** [BuildAndDestroy/CoinMarketCap_API#2]
```
(coin_market) user@kali:/root/Development/virtualenv/coin_market$ coin_market -c eos -f -i
Traceback (most recent call last):
  File "/root/Development/virtualenv/coin_market/bin/coin_market", line 11, in <module>
    load_entry_point('CoinMarketCap===2.3.5-import-csv', 'console_scripts', 'coin_market')()
  File "/root/Development/virtualenv/coin_market/lib/python2.7/site-packages/coinmarket/coinmarketcap_api.py", line 255, in main
    total_portfolio_usd = total_usd_amount(coin_portfolio_value_list)
  File "/root/Development/virtualenv/coin_market/lib/python2.7/site-packages/coinmarket/coinmarketcap_api.py", line 107, in total_usd_amount
    lambda first_position, next_position: first_position + next_position, usd_amount_list)
TypeError: reduce() of empty sequence with no initial value
```

Now that total_usd_amount is part of the flow for -c, a coin is expected to have a value. This needs to be fixed as we are no longer able to run a check against coins in general.

**Comment by BuildAndDestroy** [comment]
Fixed, exception handling will return nothing if lists are empty. This has been pushed to the origin/sort branch, version 2.4.1. This will be pushed to master once sorting has been implemented.
