### ISSUE TITLE
Version 2.3.5 - coinmarketcap.py -V throws an error

### ISSUE THREAD

**Issue by pr0d7** [BuildAndDestroy/CoinMarketCap_API#3]
```./coinmarketcap_api.py -V
Traceback (most recent call last):
  File "./coinmarketcap_api.py", line 292, in <module>
    main()
  File "./coinmarketcap_api.py", line 245, in main
    display_version()
  File "./coinmarketcap_api.py", line 66, in display_version
    __version__ = pkg_resources.require('CoinMarketCap')[0].version
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 959, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 846, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'CoinMarketCap' distribution was not found and is required by the application```

**Comment by pr0d7** [comment]
I didn't install this, I downloaded it and just ran coinmarketcap.py straight from source

**Comment by BuildAndDestroy** [comment]
I will need a new VM to test this. My current VM has the scripts installed which is interfering with my virtual environment. I'll spin up a new one and test this out.

**Comment by BuildAndDestroy** [comment]
Closing this one down, the API is dead. Creating a new tool in python3 to work with the new API.
Branch: 2020-api
